name: VaultItemExchange
version: 1.0
main: cz.krystofdolina.vaultexchange.VaultItemExchange
api-version: '1.21'
author: Kryštof Dolina
description: "Exchange items for currency using Vault. Created with AI assistance."
depend: [Vault]
commands:
  xsell:
    description: Sell items from your inventory.
    usage: /xsell <item_name> <amount>
  xwithdraw:
    description: Withdraw items using your balance.
    usage: /xwithdraw <item_name> <amount>
  xitems:
    description: List all items supported by the plugin and their prices.
    usage: /xitems
  xmoney:
    description: Check your current balance.
    usage: /xmoney